/**
 * 亚特兰蒂斯独有物种目录；形态和尺度说明见生态来源文档。
 * length 使用模型与捕食共用的游戏尺度，水层、速度和营养属于游戏设定。
 */
export const ATLANTIS_SPECIES = Object.freeze(
  [
    {
      kind: "spadefish",
      label: "大西洋白鲳",
      latin: "CHAETODIPTERUS FABER",
      category: "shoal",
      tier: 0,
      predator: false,
      length: 0.75,
      speed: 3.6,
      depthMin: 5,
      depthMax: 34,
      schoolSize: 12,
      population: 72,
      nurseryResident: true,
      nutrition: 8,
      growth: 0.018,
      color: "#d5d4c8",
      realSize: "较大个体0.75 m；最大记录约0.91 m（全长）",
      ability: "银盘结群",
      description:
        "身体高而侧扁，银色体侧有深色竖纹，背鳍和臀鳍的尖端拉长。真实个体可在礁石、沉船附近结群，本作鱼群沿遗迹浅滩活动。",
      habitatNote:
        "西大西洋近岸浅海；与其他物种共同出现在亚特兰蒂斯属于幻想集合，游戏水层与游速经过调整。",
      counter: "沿着银色鱼群拦截，连续进食后再进入外侧城区。",
    },
    {
      kind: "seahorse",
      label: "短吻海马",
      latin: "HIPPOCAMPUS HIPPOCAMPUS",
      category: "shoal",
      tier: 0,
      predator: false,
      length: 0.15,
      speed: 0.65,
      depthMin: 7,
      depthMax: 23,
      schoolSize: 1,
      population: 8,
      nurseryResident: true,
      nutrition: 8,
      growth: 0.018,
      color: "#d6bb78",
      realSize: "约0.15 m；直立模型尺度，不等同于水平鱼身长度",
      ability: "草间悬停",
      description:
        "短吻、骨环躯干与卷曲尾巴构成直立轮廓，依靠小鳍缓慢移动。尾部可攀附海草等支撑物；本作在浅滩各自的小范围内分散活动，不编成同步鱼群。",
      habitatNote:
        "东北大西洋与地中海的浅海庇护水域；微小体型提供有限营养，主要补给仍来自附近鱼群。",
      counter:
        "沿出生点前方的浅滩缓游，靠近后辨认微小轮廓；虎鲸可用声呐辅助寻找。",
    },
    {
      kind: "cuttlefish",
      label: "普通乌贼",
      latin: "SEPIA OFFICINALIS",
      category: "shoal",
      tier: 0,
      predator: false,
      length: 0.5,
      speed: 1.8,
      depthMin: 6,
      depthMax: 30,
      schoolSize: 1,
      population: 8,
      nurseryResident: true,
      nutrition: 8,
      growth: 0.018,
      color: "#cfb58e",
      realSize: "本作整体尺度0.5 m；真实外套膜可达约0.45 m，量法不同",
      ability: "裙鳍缓游",
      description:
        "扁宽外套膜两侧有连续鳍裙，头前为八条短腕和两条可伸缩摄食触腕。鳍裙波动维持缓游；现实可双向移动，本作朝向与速度为游戏姿态。",
      habitatNote:
        "东北大西洋与地中海沿岸陆架；本作在沙地附近分散活动，未启用变色或喷墨技能。",
      counter:
        "留意出生浅滩前方宽扁的轮廓；它们在各自的一小片水域活动，被吃掉后会回到原栖息区刷新。",
    },
    {
      kind: "blue_shark",
      label: "大青鲨",
      latin: "PRIONACE GLAUCA",
      category: "hunter",
      tier: 2,
      predator: true,
      length: 3.8,
      speed: 13.5,
      depthMin: 15,
      depthMax: 150,
      schoolSize: 1,
      population: 7,
      nutrition: 37.6,
      growth: 0.30027777777777775,
      color: "#548ccc",
      realSize: "较大个体约3.8 m；多数个体更小",
      ability: "外海巡猎",
      description:
        "修长身体、尖长吻与极长胸鳍适合远洋巡游，背部蓝色、腹部浅色。外礁的一只个体是离开育幼浅滩后的早期挑战，其余在外海活动。",
      habitatNote:
        "广布远洋，能进入较深水层；本作的主动追猎是游戏行为，不代表现实中常主动攻击人。",
      counter: "长到4米左右再接近外礁个体；体型不足时退回安全浅滩。",
    },
    {
      kind: "swordfish",
      label: "剑鱼",
      latin: "XIPHIAS GLADIUS",
      category: "hunter",
      tier: 2,
      predator: true,
      length: 4.2,
      speed: 15.5,
      depthMin: 35,
      depthMax: 210,
      schoolSize: 1,
      population: 6,
      nutrition: 38.4,
      growth: 0.3225,
      color: "#829bbf",
      realSize: "本作4.2 m全长包含剑状吻；最大记录约4.55 m",
      ability: "长吻巡航",
      description:
        "扁平剑状吻、高第一背鳍与新月尾构成轮廓；成体没有腹鳍，颌内无牙。它是远洋捕食者，本作在城区外侧水层独自巡游。",
      habitatNote:
        "远洋洄游鱼类，可往返表层与深水；追逐速度与碰撞尺度为游戏调整。",
      counter: "避开迎面接触，体型超过它后从侧面拦截。",
    },
    {
      kind: "helicoprion",
      label: "旋齿鲨",
      latin: "HELICOPRION SP.",
      category: "ancient",
      tier: 2,
      predator: true,
      extinct: true,
      length: 6,
      speed: 11.5,
      depthMin: 110,
      depthMax: 320,
      schoolSize: 1,
      population: 8,
      nutrition: 42,
      growth: 0.45,
      color: "#91aaa7",
      realSize: "本作6 m为重建尺度，不能视为已确认的单一物种体长",
      ability: "旋齿巡猎",
      description:
        "二叠纪古老软骨鱼类，与全头类谱系有关。螺旋齿列位于下颌正中，是持续生长的固定齿旋，不是嘴外旋转的圆锯；身体与鳍形仍有重建不确定性。",
      habitatNote:
        "已灭绝；本作复苏水层、体色与行为为幻想重建，不代表真实古海洋深度。",
      counter: "体型不足时绕开正面；长到6米以上后是通往深城的中型补给。",
    },
    {
      kind: "ichthyosaur",
      label: "切齿鱼龙",
      latin: "TEMNODONTOSAURUS TRIGONODON",
      category: "ancient",
      tier: 2,
      predator: true,
      extinct: true,
      length: 10,
      speed: 16,
      depthMin: 175,
      depthMax: 420,
      schoolSize: 1,
      population: 6,
      nutrition: 50,
      growth: 0.8944444444444446,
      color: "#728f9c",
      realSize: "约10 m的大型切齿鱼龙重建；化石鉴定与复原存在不确定性",
      ability: "古海巡猎",
      description:
        "早侏罗纪海生爬行动物，具有长有齿颌、大眼和四枚鳍肢，不是恐龙或鲸。背鳍与垂直尾鳍形成流线轮廓，尾部左右摆动推进。",
      habitatNote:
        "已灭绝；本作采用大型个体重建，复苏水层和主动追猎属于幻想设定。",
      counter: "保持侧向机动，体长超过10米后可把它作为下潜途中的大型补给。",
    },
  ].map((entry) => Object.freeze(entry)),
);
