/** 百慕大独有物种；已灭绝动物的全身比例和游戏水层属于明确标注的重建。 */
const entries = [
  [
    "queen_angelfish",
    "女王神仙鱼",
    "HOLACANTHUS CILIARIS",
    0.45,
    2.2,
    5,
    35,
    "shoal",
    false,
    "#66a9c4",
    "礁间巡游",
    "高而侧扁的蓝黄色身体、延长的背鳍臀鳍和蓝色额冠，在礁石附近各自缓慢游动。",
    "西大西洋热带礁区；本作以小范围独立居民呈现，不是真实同步大鱼群。",
    "沿安全浅滩两侧珊瑚观察，靠近后捕捉。",
    "本作0.45米全长；包括鳍尾的展示尺度。",
  ],
  [
    "triggerfish",
    "灰鳞鲀",
    "BALISTES CAPRISCUS",
    0.55,
    2.5,
    6,
    45,
    "shoal",
    false,
    "#9da99b",
    "双鳍缓游",
    "菱形躯体、小口与高位眼睛，第一背鳍具有硬棘，第二背鳍和臀鳍波动推进。",
    "大西洋近岸礁区；本作小群体、水层及营养经过玩法调整。",
    "慢游拦截礁边小群，是幼年阶段的稳定食物。",
    "本作0.55米全长的大型个体。",
  ],
  [
    "needlefish",
    "大西洋颌针鱼",
    "STRONGYLURA MARINA",
    0.9,
    4.2,
    1,
    18,
    "shoal",
    false,
    "#79bcb4",
    "水线银影",
    "细长银绿色身体、长而尖的上下颌，背鳍和臀鳍接近尾部，在水线附近游动。",
    "西大西洋近岸与河口表层；本作在安全浅滩和外海表层形成小群。",
    "看向水面下方的银线，侧向接近而不必出水。",
    "本作0.9米全长包含延长的颌。",
  ],
  [
    "barracuda",
    "大梭鱼",
    "SPHYRAENA BARRACUDA",
    1.8,
    12,
    5,
    100,
    "hunter",
    true,
    "#91b2b3",
    "表层伏击",
    "修长身体、突出的下颌、两枚分开的背鳍与匕首状牙齿。体侧斑点和暗纹打破银色轮廓。",
    "温暖近岸礁区及表层外海；主动追捕玩家是游戏行为，不代表现实常攻击人。",
    "体型足够时从侧面拦截；小角色可退回安全浅滩。",
    "本作1.8米全长，属于很大的个体。",
  ],
  [
    "tiger_shark",
    "鼬鲨",
    "GALEOCERDO CUVIER",
    5.2,
    14.5,
    5,
    220,
    "hunter",
    true,
    "#879c8f",
    "风暴巡猎",
    "宽钝吻、强壮前躯、五对鳃裂与上叶更长的尾鳍，背侧保留不规则虎纹。它能在外海表层和深水间巡猎。",
    "真实鼬鲨可在浅水和外海活动；本作追猎速度与领地是玩法设定。",
    "不要以为海面安全，离开浅滩后先观察；利用船壳或深潜避开。",
    "本作5.2米全长的大型个体；多数真实个体较小。",
  ],
  [
    "cameroceras",
    "房角石",
    "CAMEROCERAS SP.",
    6,
    10.5,
    95,
    360,
    "ancient",
    true,
    "#b7af98",
    "古壳猎手",
    "长直锥壳连接宽端的头部与腕冠。硬壳缓慢摆动，腕部起伏；这是依据壳化石的幻想复苏，软体部位不能视为已知事实。",
    "奥陶纪已灭绝头足类；腕数、眼睛、体色和游姿属于不确定的艺术复原。",
    "绕过腕冠，从侧翼接近；体型不足时利用沉船破口脱身。",
    "本作6米整体重建尺度；不声称化石证明了完整动物的精确体长。",
  ],
  [
    "livyatan",
    "梅尔维尔鲸",
    "LIVYATAN MELVILLEI",
    17.5,
    18,
    70,
    530,
    "ancient",
    true,
    "#82939c",
    "巨颌巡猎",
    "粗壮头部和强力下颌，上下颌均有大牙，鳍肢与水平尾鳍构成猛食鲸轮廓。它在沉船外侧和深水路线巡游。",
    "已灭绝的猛食型抹香鲸类；身体、鳍形与体色是根据部分头骨作出的重建。",
    "不是所有远古巨兽都待在最深处，接近沉船前先声呐侦察。",
    "本作17.5米为较大体长估计端点；没有完整骨架确定这一数值。",
  ],
];
export const BERMUDA_SPECIES = Object.freeze(
  entries.map(
    ([
      kind,
      label,
      latin,
      length,
      speed,
      depthMin,
      depthMax,
      category,
      predator,
      color,
      ability,
      description,
      habitatNote,
      counter,
      realSize,
    ]) =>
      Object.freeze({
        kind,
        label,
        latin,
        length,
        speed,
        depthMin,
        depthMax,
        category,
        predator,
        color,
        ability,
        description,
        habitatNote,
        counter,
        realSize,
        tier: predator ? 2 : 0,
        extinct: category === "ancient",
        schoolSize: 1,
        population: 6,
        nutrition: predator ? 30 + length * 2 : 8,
        growth: predator ? 0.2 + (length / 6) ** 2 * 0.25 : 0.018,
      }),
  ),
);
