import { EUROPA_WORLD } from "./europa_config.js";

/** 原创外星生命数据，图鉴分类和实际营养/猎手属性独立。 */
export const EUROPA_SPECIES = Object.freeze(
  [
    {
      kind: "glass_seed",
      label: "玻种游体",
      latin: "EUROPA LIFEFORM E-01",
      length: 0.9,
      population: 52,
      speed: 2.4,
      trophicRole: "grazer",
      tier: 0,
      depthMin: 5,
      depthMax: 40,
      nutrition: 8,
      growth: 0.016,
      predator: false,
      category: "alien",
      color: "#528b9a",
      schoolSize: 8,
      ability: "缓慢滤食",
      description: "六片实体棱晶壳包围琥珀色核心，甲片接缝和成对舵叶清晰可辨。",
      habitatNote: "冰下幻想生态；沿盐脉、悬生群落与热泉寻找食物。",
      counter: "观察体长；成长后才向更深的栖地探索，利用岩拱和冲刺避开猎手。",
      realSize: "幻想物种，非已发现的外星生命；尺寸与行为是原创游戏设定。",
      schoolAnchors: [
        [0, -18, 57],
        [-18, -20, 22],
        [18, -18, -20],
        [-14, -20, 90],
      ],
      layeredSchools: true,
      nurseryResident: true,
    },
    {
      kind: "ribbon_spore",
      label: "缎带孢游",
      latin: "EUROPA LIFEFORM E-02",
      length: 1.4,
      population: 40,
      speed: 2.1,
      trophicRole: "grazer",
      tier: 0,
      depthMin: 8,
      depthMax: 65,
      nutrition: 10,
      growth: 0.035,
      predator: false,
      category: "alien",
      color: "#817aaa",
      schoolSize: 8,
      ability: "缓慢滤食",
      description: "细长膜带围绕连续中脊起伏，尾端分出三条细丝；没有桶状外套。",
      habitatNote: "冰下幻想生态；沿盐脉、悬生群落与热泉寻找食物。",
      counter: "观察体长；成长后才向更深的栖地探索，利用岩拱和冲刺避开猎手。",
      realSize: "幻想物种，非已发现的外星生命；尺寸与行为是原创游戏设定。",
      schoolAnchors: [
        [-15, -23, 48],
        [16, -27, -12],
        [-20, -32, -68],
        [20, -36, -100],
      ],
      layeredSchools: true,
      nurseryResident: true,
    },
    {
      kind: "tripod_bloom",
      label: "三瓣浮蕾",
      latin: "EUROPA LIFEFORM E-03",
      length: 2.2,
      population: 28,
      speed: 2.0,
      trophicRole: "grazer",
      tier: 0,
      depthMin: 12,
      depthMax: 80,
      nutrition: 16,
      growth: 0.09,
      predator: false,
      category: "alien",
      color: "#b67a69",
      schoolSize: 8,
      ability: "缓慢滤食",
      description:
        "三片饱满的肉质瓣放射展开，瓣脊与感知节点围绕中央滤食口缓慢摆动。",
      habitatNote: "冰下幻想生态；沿盐脉、悬生群落与热泉寻找食物。",
      counter: "观察体长；成长后才向更深的栖地探索，利用岩拱和冲刺避开猎手。",
      realSize: "幻想物种，非已发现的外星生命；尺寸与行为是原创游戏设定。",
      schoolAnchors: [
        [22, -28, 40],
        [-24, -32, -42],
        [24, -40, -110],
      ],
      layeredSchools: true,
      nurseryResident: true,
    },
    {
      kind: "sail_crawler",
      label: "帆脊巡游者",
      latin: "EUROPA LIFEFORM E-04",
      length: 3.2,
      population: 20,
      speed: 3.4,
      trophicRole: "grazer",
      tier: 1,
      depthMin: 25,
      depthMax: 145,
      nutrition: 22,
      growth: 0.15,
      predator: false,
      category: "alien",
      color: "#60716c",
      schoolSize: 8,
      ability: "缓慢滤食",
      description:
        "层叠硬甲托起背帆，六条带关节的桨肢交替划水；前方长须探测盐流。",
      habitatNote: "冰下幻想生态；沿盐脉、悬生群落与热泉寻找食物。",
      counter: "观察体长；成长后才向更深的栖地探索，利用岩拱和冲刺避开猎手。",
      realSize: "幻想物种，非已发现的外星生命；尺寸与行为是原创游戏设定。",
      schoolAnchors: [
        [-80, -65, -125],
        [60, -78, -145],
        [-100, -100, -180],
      ],
      layeredSchools: true,
      nurseryResident: false,
    },
    {
      kind: "lantern_pod",
      label: "灯荚游体",
      latin: "EUROPA LIFEFORM E-05",
      length: 4.8,
      population: 18,
      speed: 3.0,
      trophicRole: "grazer",
      tier: 1,
      depthMin: 55,
      depthMax: 220,
      nutrition: 28,
      growth: 0.24,
      predator: false,
      category: "alien",
      color: "#716387",
      schoolSize: 8,
      ability: "缓慢滤食",
      description: "五道弓形硬肋保护内凹的发光腔，后方五片短裙叶轻轻摆动。",
      habitatNote: "冰下幻想生态；沿盐脉、悬生群落与热泉寻找食物。",
      counter: "观察体长；成长后才向更深的栖地探索，利用岩拱和冲刺避开猎手。",
      realSize: "幻想物种，非已发现的外星生命；尺寸与行为是原创游戏设定。",
      schoolAnchors: [
        [-110, -95, -165],
        [35, -145, -235],
        [95, -180, -280],
      ],
      layeredSchools: true,
      nurseryResident: false,
    },
    {
      kind: "veil_glider",
      label: "帷翼滑翔者",
      latin: "EUROPA LIFEFORM E-06",
      length: 6.5,
      population: 16,
      speed: 4.2,
      trophicRole: "grazer",
      tier: 1,
      depthMin: 120,
      depthMax: 350,
      nutrition: 36,
      growth: 0.38,
      predator: false,
      category: "alien",
      color: "#6a879b",
      schoolSize: 8,
      ability: "缓慢滤食",
      description: "宽阔的双层风筝翼围绕实体龙骨舒展，细长分叉尾保持方向。",
      habitatNote: "冰下幻想生态；沿盐脉、悬生群落与热泉寻找食物。",
      counter: "观察体长；成长后才向更深的栖地探索，利用岩拱和冲刺避开猎手。",
      realSize: "幻想物种，非已发现的外星生命；尺寸与行为是原创游戏设定。",
      schoolAnchors: [
        [80, -210, -310],
        [110, -250, -365],
        [-45, -290, -385],
      ],
      layeredSchools: true,
      nurseryResident: false,
    },
    {
      kind: "forkjaw_stalker",
      label: "裂颌潜猎者",
      latin: "EUROPA LIFEFORM E-07",
      length: 8.5,
      population: 12,
      speed: 18,
      trophicRole: "hunter",
      tier: 2,
      depthMin: 75,
      depthMax: 350,
      nutrition: 42,
      growth: 0.52,
      predator: true,
      category: "alien",
      color: "#4a5d72",
      schoolSize: 1,
      ability: "脉冲突进",
      description: "重叠胸甲与两把弯曲钳颌形成鲜明轮廓，钳颌在突进前张开。",
      habitatNote: "冰下幻想生态；沿盐脉、悬生群落与热泉寻找食物。",
      counter: "观察体长；成长后才向更深的栖地探索，利用岩拱和冲刺避开猎手。",
      realSize: "幻想物种，非已发现的外星生命；尺寸与行为是原创游戏设定。",
      spawnAnchors: [
        [-160, -110, -190],
        [150, -220, -340],
        [-140, -280, -400],
      ],
      residentRadius: 35,
      hunterTerritory: {
        minX: -265,
        maxX: 265,
        minZ: -965,
        maxZ: -130,
        center: {
          x: -160,
          y: -110,
          z: -190,
        },
      },
    },
    {
      kind: "crown_filterer",
      label: "冠环滤食者",
      latin: "EUROPA LIFEFORM E-08",
      length: 11.5,
      population: 10,
      speed: 5,
      trophicRole: "grazer",
      tier: 1,
      depthMin: 200,
      depthMax: 470,
      nutrition: 50,
      growth: 0.75,
      predator: false,
      category: "alien",
      color: "#a07182",
      schoolSize: 8,
      ability: "缓慢滤食",
      description:
        "梨形外套连接八条粗根细尖的长腕，腕上滤食褶与感知晶面形成外星八腕体态。",
      habitatNote: "冰下幻想生态；沿盐脉、悬生群落与热泉寻找食物。",
      counter: "观察体长；成长后才向更深的栖地探索，利用岩拱和冲刺避开猎手。",
      realSize: "幻想物种，非已发现的外星生命；尺寸与行为是原创游戏设定。",
      schoolAnchors: [
        [100, -255, -360],
        [-90, -365, -475],
        [80, -400, -500],
      ],
      layeredSchools: true,
      nurseryResident: false,
    },
    {
      kind: "prism_hunter",
      label: "棱冠猎手",
      latin: "EUROPA LIFEFORM E-09",
      length: 14.5,
      population: 8,
      speed: 20,
      trophicRole: "hunter",
      tier: 2,
      depthMin: 240,
      depthMax: 550,
      nutrition: 60,
      growth: 1.1,
      predator: true,
      category: "alien",
      color: "#546c91",
      schoolSize: 1,
      ability: "脉冲突进",
      description:
        "三面硬刃包住流线核心，三枚尾舵在突进前收拢；整体呈棱形飞镖状。",
      habitatNote: "冰下幻想生态；沿盐脉、悬生群落与热泉寻找食物。",
      counter: "观察体长；成长后才向更深的栖地探索，利用岩拱和冲刺避开猎手。",
      realSize: "幻想物种，非已发现的外星生命；尺寸与行为是原创游戏设定。",
      spawnAnchors: [
        [135, -300, -410],
        [140, -395, -510],
        [-155, -450, -560],
      ],
      residentRadius: 35,
      hunterTerritory: {
        minX: -265,
        maxX: 265,
        minZ: -965,
        maxZ: -130,
        center: {
          x: -150,
          y: -300,
          z: -410,
        },
      },
    },
    {
      kind: "bell_carrier",
      label: "浮钟巨载",
      latin: "EUROPA LIFEFORM E-10",
      length: 18,
      population: 8,
      speed: 5.5,
      trophicRole: "giant",
      tier: 1,
      depthMin: 350,
      depthMax: 710,
      nutrition: 74,
      growth: 1.4,
      predator: false,
      category: "alien",
      color: "#638d83",
      schoolSize: 8,
      ability: "缓慢滤食",
      description:
        "宽大波瓣伞罩下垂着分支触带和小型副钟，主体像漂浮的钟罩群落而非游鱼。",
      habitatNote: "冰下幻想生态；沿盐脉、悬生群落与热泉寻找食物。",
      counter: "观察体长；成长后才向更深的栖地探索，利用岩拱和冲刺避开猎手。",
      realSize: "幻想物种，非已发现的外星生命；尺寸与行为是原创游戏设定。",
      schoolAnchors: [
        [-75, -425, -530],
        [65, -490, -590],
        [-110, -550, -620],
      ],
      layeredSchools: true,
      nurseryResident: false,
    },
    {
      kind: "siphon_colossus",
      label: "虹吸巨腹",
      latin: "EUROPA LIFEFORM E-11",
      length: 21,
      population: 6,
      speed: 6,
      trophicRole: "giant",
      tier: 1,
      depthMin: 420,
      depthMax: 790,
      nutrition: 82,
      growth: 1.9,
      predator: false,
      category: "alien",
      color: "#8c7b66",
      schoolSize: 6,
      ability: "缓慢滤食",
      description:
        "长肋管体向后收细，前端滤口与成对外伸虹吸管吸入水流，腹裙低频摆动。",
      habitatNote: "冰下幻想生态；沿盐脉、悬生群落与热泉寻找食物。",
      counter: "观察体长；成长后才向更深的栖地探索，利用岩拱和冲刺避开猎手。",
      realSize: "幻想物种，非已发现的外星生命；尺寸与行为是原创游戏设定。",
      schoolAnchors: [
        [-100, -495, -590],
        [90, -590, -650],
        [-95, -650, -700],
      ],
      layeredSchools: true,
      nurseryResident: false,
    },
    {
      kind: "spiral_grazer",
      label: "螺冠巨游",
      latin: "EUROPA LIFEFORM E-12",
      length: 24,
      population: 6,
      speed: 7,
      trophicRole: "giant",
      tier: 1,
      depthMin: 520,
      depthMax: 820,
      nutrition: 88,
      growth: 2.4,
      predator: false,
      category: "alien",
      color: "#647f88",
      schoolSize: 6,
      ability: "缓慢滤食",
      description:
        "实体盘旋甲壳有连续螺纹与壳缝，柔软腹足、侧鳍和前触须支撑缓慢游动。",
      habitatNote: "冰下幻想生态；沿盐脉、悬生群落与热泉寻找食物。",
      counter: "观察体长；成长后才向更深的栖地探索，利用岩拱和冲刺避开猎手。",
      realSize: "幻想物种，非已发现的外星生命；尺寸与行为是原创游戏设定。",
      schoolAnchors: [
        [-110, -620, -675],
        [100, -680, -735],
        [-170, -740, -830],
      ],
      layeredSchools: true,
      nurseryResident: false,
    },
    {
      kind: "rift_reaver",
      label: "裂谷掠夺者",
      latin: "EUROPA LIFEFORM E-13",
      length: 29,
      population: 3,
      speed: 24,
      trophicRole: "hunter",
      tier: 2,
      depthMin: 490,
      depthMax: 810,
      nutrition: 94,
      growth: 3.2,
      predator: true,
      category: "alien",
      color: "#625968",
      schoolSize: 1,
      ability: "脉冲突进",
      description:
        "细长蛇形躯干覆有倒钩甲片与背刺，尾段独立摆动，前方弯钩颌在猎袭前张开。",
      habitatNote: "冰下幻想生态；沿盐脉、悬生群落与热泉寻找食物。",
      counter: "观察体长；成长后才向更深的栖地探索，利用岩拱和冲刺避开猎手。",
      realSize: "幻想物种，非已发现的外星生命；尺寸与行为是原创游戏设定。",
      spawnAnchors: [
        [-170, -525, -610],
        [-185, -685, -760],
        [175, -760, -900],
      ],
      residentRadius: 35,
      hunterTerritory: {
        minX: -265,
        maxX: 265,
        minZ: -965,
        maxZ: -130,
        center: {
          x: 175,
          y: -595,
          z: -675,
        },
      },
    },
    {
      kind: "void_siphon",
      label: "虚渊吞吸者",
      latin: "EUROPA LIFEFORM E-14",
      length: 32,
      population: 2,
      speed: 25,
      trophicRole: "hunter",
      tier: 2,
      depthMin: 640,
      depthMax: 830,
      nutrition: 98,
      growth: 3.7,
      predator: true,
      category: "alien",
      color: "#414a68",
      schoolSize: 1,
      ability: "脉冲突进",
      description:
        "四瓣厚钳围住深陷口腔，环形甲带包住渐细管体，尾部双舵缓慢起伏。",
      habitatNote: "冰下幻想生态；沿盐脉、悬生群落与热泉寻找食物。",
      counter: "观察体长；成长后才向更深的栖地探索，利用岩拱和冲刺避开猎手。",
      realSize: "幻想物种，非已发现的外星生命；尺寸与行为是原创游戏设定。",
      spawnAnchors: [
        [-135, -745, -790],
        [140, -735, -795],
      ],
      residentRadius: 35,
      hunterTerritory: {
        minX: -265,
        maxX: 265,
        minZ: -965,
        maxZ: -130,
        center: {
          x: -190,
          y: -745,
          z: -890,
        },
      },
    },
    {
      kind: "brine_rosette",
      label: "盐泉旋花",
      latin: "EUROPA LIFEFORM E-15",
      length: 0.8,
      population: 10,
      speed: 0.8,
      trophicRole: "resident",
      tier: 0,
      depthMin: 5,
      depthMax: 90,
      nutrition: 7,
      growth: 0.012,
      predator: false,
      category: "alien",
      color: "#927252",
      schoolSize: 1,
      ability: "底栖巡游",
      description:
        "六片低矮硬壳组成底栖放射盘，中央组织轻轻脉动；尺寸为最大直径。",
      habitatNote: "冰下幻想生态；沿盐脉、悬生群落与热泉寻找食物。",
      counter: "观察体长；成长后才向更深的栖地探索，利用岩拱和冲刺避开猎手。",
      realSize: "幻想物种，非已发现的外星生命；尺寸与行为是原创游戏设定。",
      spawnAnchors: [
        [-25, -20, 38],
        [26, -25, -35],
      ],
      residentRadius: 8,
      benthic: true,
      floorOffset: 0.2,
    },
    {
      kind: "hinge_walker",
      label: "铰壳行者",
      latin: "EUROPA LIFEFORM E-16",
      length: 2,
      population: 8,
      speed: 1.2,
      trophicRole: "resident",
      tier: 0,
      depthMin: 10,
      depthMax: 155,
      nutrition: 15,
      growth: 0.08,
      predator: false,
      category: "alien",
      color: "#607b6e",
      schoolSize: 1,
      ability: "底栖巡游",
      description:
        "层叠背甲、长感知须与六条分节关节足形成爬行体态，脚尖贴近基底行走。",
      habitatNote: "冰下幻想生态；沿盐脉、悬生群落与热泉寻找食物。",
      counter: "观察体长；成长后才向更深的栖地探索，利用岩拱和冲刺避开猎手。",
      realSize: "幻想物种，非已发现的外星生命；尺寸与行为是原创游戏设定。",
      spawnAnchors: [
        [-75, -70, -125],
        [65, -95, -170],
      ],
      residentRadius: 8,
      benthic: true,
      floorOffset: 0.27,
    },
  ].map((entry) =>
    Object.freeze({
      ...entry,
      ...(entry.predator
        ? {
            hunterAbility: "shark",
            hunterTell: "外星猎手收拢膜叶 · 侧向闪避即将到来的突进",
          }
        : {}),
      schoolAnchors: entry.schoolAnchors
        ? Object.freeze(entry.schoolAnchors.map((a) => Object.freeze(a)))
        : undefined,
      spawnAnchors: entry.spawnAnchors
        ? Object.freeze(entry.spawnAnchors.map((a) => Object.freeze(a)))
        : undefined,
      worldBounds: EUROPA_WORLD,
      cityHabitat: true,
    }),
  ),
);
