/** 海沟独有生物保留实际体型；跨层大型猎物另由地图数据明确标注为幻想生态。 */
const entries = [
  [
    "moorish_idol",
    "镰鱼",
    "ZANCLUS CORNUTUS",
    0.23,
    2.1,
    4,
    38,
    false,
    "#eedb92",
    "长旗礁影",
    "侧扁的黑白黄条纹身体、细长吻部和飘带状背鳍，在浅水礁坡间缓慢转向。",
    "印度太平洋礁区；本作的小群密度经过玩法调整。",
    "留意安全浅滩两侧的黑白条纹。",
  ],
  [
    "lanternfish",
    "灯笼鱼",
    "MYCTOPHIDAE",
    0.18,
    2.7,
    70,
    250,
    false,
    "#85d5e2",
    "腹侧星光",
    "银黑色小鱼，大眼与腹侧排列的发光器官构成细碎星河。",
    "中层海洋发光鱼类；本作深度与小群规模是游戏安排。",
    "在第一段岩壁的蓝色星点附近寻找鱼群。",
  ],
  [
    "barreleye",
    "管眼鱼",
    "MACROPINNA MICROSTOMA",
    0.15,
    1.4,
    140,
    260,
    false,
    "#96bcb8",
    "透明穹顶",
    "头顶透明罩保护两枚向上观察的绿色管状眼，胸鳍像细薄扇面，在水中悬停。",
    "现实见于北太平洋中层；本作移入马里亚纳幻想海域，保留微小体型。",
    "这是观察型居民；使用声呐定位，不要依赖它补充成年能量。",
  ],
  [
    "dragonfish",
    "深海龙鱼",
    "STOMIIDAE",
    0.38,
    3.4,
    220,
    520,
    false,
    "#75a9ce",
    "冷光长须",
    "墨黑的细长身体带有两列腹侧发光器，细长下颌须在口前弯曲，针状牙齿错落排列。",
    "深海龙鱼类的综合造型；发光器与捕食习性参考真实类群，仍是小鱼。",
    "沿暗色岩壁观察零星的蓝色光点。",
  ],
  [
    "snailfish",
    "马里亚纳狮子鱼",
    "PSEUDOLIPARIS SWIREI",
    0.28,
    1.7,
    1550,
    2025,
    false,
    "#ecbcb0",
    "超深渊居民",
    "淡粉色胶质身体、宽圆头和蝌蚪状细尾，背鳍臀鳍连续包围尾部，胸鳍宽大。",
    "马里亚纳超深渊约6000至8000米水层的真实小鱼；最底部彩蛋不被当成真实鱼类栖地。",
    "第二道关卡后观察粉白小居民；成年补给仍依靠幻想巨兽。",
  ],
  [
    "goblin_shark",
    "欧氏尖吻鲛",
    "MITSUKURINA OWSTONI",
    4.2,
    13,
    100,
    460,
    true,
    "#cbb0b8",
    "长吻伏猎",
    "长而扁平的剑状吻突、可突出的颌、粉灰皮肤、小背鳍与长上叶尾鳍，构成独特深水鲨鱼轮廓。",
    "真实深水鲨鱼；本作主动追逐与速度属于游戏设定，不代表现实行为。",
    "先判断体型；小角色用岩壁和冲刺脱离追逐。",
  ],
];
export const MARIANA_SPECIES = Object.freeze(
  entries.map(
    ([
      kind,
      label,
      latin,
      length,
      speed,
      depthMin,
      depthMax,
      predator,
      color,
      ability,
      description,
      habitatNote,
      counter,
    ]) =>
      Object.freeze({
        kind,
        label,
        latin,
        length,
        speed,
        depthMin,
        depthMax,
        predator,
        color,
        ability,
        description,
        habitatNote,
        counter,
        category: predator ? "hunter" : "shoal",
        tier: predator ? 2 : 0,
        population: 8,
        schoolSize: 1,
        nutrition: predator ? 38 : 8,
        growth: predator ? 0.34 : 0.016,
        realSize: "模型采用物种参考体型；密度、出生点和战斗行为属于玩法调整。",
      }),
  ),
);
