import { odysseySeabedHeight as floor } from "./odyssey_config.js";
const homes = (points, clearance) =>
  points.map(([x, z]) => [x, floor(x, z) + clearance, z]);

/** 新增物种占用分散的实际水层；群体种少量成群，大型生物独立补给。 */
export const ODYSSEY_EXTRA_ROWS = [
  [
    "iris_cuttlefish",
    "虹纹乌贼",
    "Iris Cuttlefish",
    1.1,
    3.4,
    "#aa677d",
    "扁椭圆的外套膜围着一圈起伏的侧鳍，八只短腕与两根捕食长腕收拢在头前。它们沿浅湾石隙缓慢悬游，皮肤的玫紫与砂金纹在转身时交替显现。",
    "An oval mantle is edged by rippling lateral fins; eight short arms and two feeding tentacles gather before the head. These cuttlefish hover beside shallow cracks, turning rose-violet and sand-gold patterns toward the light.",
    homes(
      [
        [-40, 25],
        [45, -65],
        [-75, -180],
        [90, -245],
        [-90, -330],
      ],
      22,
    ),
    2,
    false,
  ],
  [
    "amphora_hermit",
    "陶壶寄居蟹",
    "Amphora Hermit",
    2.2,
    2.8,
    "#ae806c",
    "古陶壶的断口成了柔软腹部的庇护所，细长触角、柄眼与大小不等的螯从壶口伸出。寄居蟹以数对关节足绕过贝园，在遗物间寻找下一处容身之所。",
    "Broken amphorae shelter soft abdomens while antennae, stalked eyes and unequal pincers emerge from the opening. Jointed legs carry these hermits around shell gardens in search of another refuge among the relics.",
    homes(
      [
        [45, -175],
        [-55, -245],
        [85, -325],
        [-80, -410],
        [50, -510],
        [-95, -585],
      ],
      9,
    ),
    1,
    false,
  ],
  [
    "aegean_jelly",
    "爱琴灯水母",
    "Aegean Lantern Jelly",
    2.6,
    3,
    "#ac98b7",
    "圆伞内的放射纹像折起的薄纱，四条褶边口腕垂在细触须之间。伞体有节律地收缩，又缓缓张开，让它穿过花园上方的静水；淡紫光泽来自体色，不是刺眼的灯。",
    "Radial markings lie beneath a domed bell like folded gauze, with four frilled oral arms among slender tentacles. Rhythmic bell contractions carry it through still water above the gardens; the violet sheen is body color rather than a glaring lamp.",
    homes(
      [
        [-80, -200],
        [100, -310],
        [-115, -440],
      ],
      65,
    ),
    2,
    false,
  ],
  [
    "silver_pipefish",
    "银叶海龙",
    "Silverleaf Pipefish",
    4.5,
    5,
    "#9aafa6",
    "管状长吻连着窄小头部，骨环护住细长躯干，叶片般的皮瓣沿两侧展开。它常与海草同向轻摆，缓缓横向波动的尾身让陌生人误把它当成一片漂游的银叶。",
    "A tubular snout joins a small head above a slender, ring-armored body with leaflike lobes. It sways in the direction of seagrass, its gently undulating tail often mistaken for a drifting silver leaf.",
    homes(
      [
        [-85, -175],
        [115, -250],
        [-115, -340],
        [135, -450],
        [-125, -555],
        [110, -650],
      ],
      28,
    ),
    1,
    false,
  ],
  [
    "aegis_sturgeon",
    "盾鳞鲟兽",
    "Aegis Sturgeon",
    9,
    16,
    "#718781",
    "铲形长吻先探入水流，四条口前触须搜寻沙地，五列骨盾护住强壮鱼身。高扬的尾叶有上下不对称的轮廓，沿古代航道巡猎时，骨甲像一列沉默的盾牌。",
    "A shovel-shaped snout leads four sensory barbels over the sand, while five rows of scutes protect a muscular body. An asymmetrical tail drives the hunter along ancient sea roads, its armor resembling a procession of silent shields.",
    homes(
      [
        [80, -300],
        [-115, -390],
        [115, -490],
        [-145, -600],
        [130, -725],
        [-115, -830],
      ],
      45,
    ),
    1,
    true,
  ],
  [
    "thalassa_manta",
    "潮歌巨鳐",
    "Thalassa Manta",
    16,
    8.5,
    "#568598",
    "宽阔胸翼从厚实中央盘身展开，起伏从翼根传向翼尖；头前一对卷起的头鳍引导水流进入宽口。它独自越过领主领地外的礁肩，身后长尾在水中留下一道细弧。",
    "Broad pectoral wings spread from a thick central disc, waves passing from roots to tips. Paired cephalic lobes guide water into a wide mouth. Solitary mantas cross reef shoulders outside guardian territory, a slender tail tracing their passage.",
    homes(
      [
        [-95, -425],
        [120, -570],
        [90, -765],
        [-90, -960],
      ],
      60,
    ),
    1,
    false,
  ],
  [
    "cerulean_hound",
    "碧浪海犬",
    "Cerulean Sea Hound",
    21,
    23,
    "#52798e",
    "宽阔胸颈与长须吻部像守海的猛兽，四片肌肉鳍肢紧贴流线躯干。它用前鳍转向，后鳍与尾身共同推进，在深水侧沟追逐离群猎物，厚重外形并不妨碍迅速折返。",
    "A broad chest and whiskered muzzle resemble a fierce guardian of the sea. Four muscular flippers join a streamlined trunk; foreflippers steer while the hind pair and rear body provide thrust. It hunts isolated prey in deep side gullies and turns quickly despite its powerful build.",
    homes(
      [
        [-145, -620],
        [145, -820],
        [-160, -1000],
      ],
      65,
    ),
    1,
    true,
  ],
];
